### ISSUE TITLE
Feature request: Minimize to tray

### ISSUE THREAD

**Issue by Devocub** [miniant-git/REAL#1]
Add ability to minimize the program to tray.
Also starting program with -hide argument should run it minimized to being able to put it shortcut in startup folder.

**Comment by Grasscirno** [comment]
Would love to see this implemented :)

**Comment by roaroftime** [comment]
This would be great, I already have enough stuff on my taskbar and running it on startup causes the window to pop up in the front as well.

**Comment by miniant-git** [comment]
The feature has now been released in REAL v0.2.0. Closing the issue.
