### ISSUE TITLE
Allow choosing a non-default audio output, in order to support Voicemeeter and other middle-man situations.

### ISSUE THREAD

**Issue by Kiefy** [miniant-git/REAL#16]
Firstly, thank you for this tool. it's the only working solution for an audio popping (constantly creating new sound sources) issue I am having with Onboard Realtek audio recently, and it works great.  But if I also use Voicemeeter, which requires me to use it's own virtual output as Windows default [https://i.imgur.com/JRzQ0j0.png](https://i.imgur.com/JRzQ0j0.png), applying REAL to this virtual output doesn't work.  It appears the audio popping is only fixed when REAL is applied to the Hardware Realtek output, not the virtual.

~So what I have to do on every system start is:~
~1. Close Voicemeeter.~
~2. Reselect hardware (Speakers) output as windows default.~
~3. Apply REAL.~
~4. Relaunch Voicemeeter.~
~5. Switch back to Voicemeeter virtual output as windows default.~

**EDIT:** Ok, so it seems this startup-sequence doesn't actually work.  REAL only seems to work when Hardware input remains default.  Is that because REAL is only looking at default output? or something else?  I thought about Closing the issue when I discovered this. but maybe you still can help? :)

**Describe the solution you'd like**
It would be great if I could target a specific non-default output as an arg.
ie. REAL.exe --tray --device "Realtek High Definition Audio"
Issue with that is both analog and digital outputs have the same name. [https://i.imgur.com/6OFsoYr.png](https://i.imgur.com/6OFsoYr.png) but I wouldn't mind disabling the one I don't need if it helps.  Though I suspect there is some way to see a unique ID somewhere?

Maybe add an arg to --list devices unique names or assign them a unique ID?

**Comment by GameFuzzy** [comment]
I'd also like to know whether or not this is possible

**Comment by april83c** [comment]
for anyone stumbling upon this issue - if you need it for VB cable, you can do this through the VB cable control panels, no need to use REAL 

<img width="359" height="185" alt="Image" src="https://github.com/user-attachments/assets/8184b647-ff52-47d1-9dc9-31d419af6a25" />

**Comment by thomasfordii** [comment]
I would like to unsubscribe. I don’t believe that it is even legal to force people to sign into an account in order to unsubscribe? I don’t know how to sign into your system so I don’t have any way to unsubscribe to it. Thank you.Otherwise, I can just block these emails.TSent from my iPhoneOn Jul 27, 2025, at 1:41 PM, April ***@***.***> wrote:﻿april83c left a comment (miniant-git/REAL#16)
for anyone stumbling upon this issue - if you need it for VB cable, you can do this through the VB cable control panels, no need to use REAL
image.png (view on web)
