### ISSUE TITLE
Win 11?

### ISSUE THREAD

**Issue by ghost** [miniant-git/REAL#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by d1scolor** [comment]
Win 11 is not a problem
<img width="424" alt="Snipaste_2024-01-19_15-11-41" src="https://github.com/miniant-git/REAL/assets/50088090/6c640788-8718-4232-920f-e13dd8e58623">
