### ISSUE TITLE
Unable to select "High Definition Audio Device"

### ISSUE THREAD

**Issue by BinkanSalaryman** [miniant-git/REAL#6]
Hi there, I come from [this](https://www.reddit.com/r/osugame/comments/hqoakj/tutorial_removing_perceivable_latency_for_good/) reddit thread, but sadly I can't spot the "High Definition Audio Device" mentioned in the [README](https://github.com/miniant-git/REAL/blob/master/README.md#setup). I'm aware this isn't directly related to the REAL software and am sorry if I bothered you.

### REAL:
![image](https://user-images.githubusercontent.com/6740731/87475500-3431f400-c625-11ea-9006-079838d7449e.png)

### Device Manager:
![image](https://user-images.githubusercontent.com/6740731/87476194-42ccdb00-c626-11ea-8cb3-99c757e37e30.png)
---
![image](https://user-images.githubusercontent.com/6740731/87475587-56c40d00-c625-11ea-9c64-3938dfde2e9f.png)
---
![image](https://user-images.githubusercontent.com/6740731/87475447-16fd2580-c625-11ea-84db-fbc8578469db.png)
---
![image](https://user-images.githubusercontent.com/6740731/87475722-8d9a2300-c625-11ea-8224-0ddb8f30d87e.png)

**Comment by SnowLire** [comment]
You need to select your device in **_Sound, Video and Game Controllers_**, afterward, change the driver for **_Realtek(R) Audio_** to HD Audio Device.

**Comment by BinkanSalaryman** [comment]
@SnowLire Your solution worked (after a quick restart). Thank you, sir!
