### ISSUE TITLE
CPU doesn't downclock

### ISSUE THREAD

**Issue by Puncia** [miniant-git/REAL#7]
**REAL version**: 0.2.0

I made a GIF which should be pretty self-explanatory but basically whenever REAL is open my i5-4690 is kept at a high frequency.

![qWhQVv8NR0](https://user-images.githubusercontent.com/4633311/88479719-83472580-cf51-11ea-9275-7c567e46d6f0.gif)

Here's all 4 of my cores being monitored with HWiNFO64.

**Comment by miniant-git** [comment]
Thank you for opening an issue.  I was able to reproduce this, but unfortunately I won't be able to fix it. 

To explain what's happening here, when REAL requests low audio latency, Windows enters a special mode of operation. The behaviour you observe is a side-effect of having this special mode enabled, and seems to work as designed by Windows audio engineers.

I'll mention this behaviour somewhere in the README.
